### ISSUE TITLE
[Prework iOS 1] Tips Calculator - Review my app #1

### ISSUE THREAD

**Issue by giaotuancse** [giaotuancse/tipscalculator#1]
My app is complete. Please review /cc @chug2k

**Comment by chug2k** [comment]
:+1:  Excellent job with the Tip Calculator! Congratulations, you're accepted to the class - see you on November 9th! We will email you at your gmail.com email address soon with information about exactly where to meet. 

**I think you are on Xcode 6.x. Please upgrade to XCode 7!**
- Great job with the validation on the settings page to make sure the values are valid! 
- However, on the left side of the Settings page, you should be using `UILabel`, not `UITextField` for the "Minimum", "Maxmium", and "Default" text.
- Good job with NSUserDefaults.
- Great usage of `UITableView`. We'll learn more about that in Week #1, about how to make dynamic tables.
- Coding style cleanup: Please use consistent spacing. No semicolons, and (parentheses) around if statements are not necessary. Please follow guidelines from the style guide here: https://github.com/raywenderlich/swift-style-guide.

/cc @marcusellison @harley @minhchau273

**Comment by chug2k** [comment]
lol
